### PR TITLE
Fix Storage Bug, Add checks for FindExpenseCommand, Refactor isFixed user input

### LINKED ISSUE #112: Add checks for Find Expense
Add checks for Find Expense Command Parser

### LINKED ISSUE #124: Fix Storage Bug, Refactor isFixed User input
Fix Storage Bug, Refactor "t" and "f" to "y" and "n" for isFixed

### PR DESCRIPTION
**Pull request by yanlynnnnn**
Fix Storage Bug, Add checks for FindExpenseCommand, Refactor isFixed user input from "t" and "f" to "y" and "n"

### CODE REVIEW

File: src/main/java/seedu/address/MainApp.java [hunk 1]
```diff
@@ -210,7 +210,7 @@ private ReadOnlyServiceManager initServiceManager(Storage storage) {
     private ReadOnlyExpenseTracker initExpenseTracker(Storage storage) {
         ReadOnlyExpenseTracker expenseTracker;
         try {
-            Optional<ReadOnlyExpenseTracker> expenseTrackerOptional = storage.readExpenseTracker();
+            Optional<ReadOnlyExpenseTracker> expenseTrackerOptional;
             expenseTrackerOptional = storage.readExpenseTracker();
```
Comment (galvinleow) [inline src/main/java/seedu/address/MainApp.java:251]: Can just make this 2 into 1 line?

File: src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java [hunk 2]
```diff
@@ -21,7 +20,7 @@
     @Override
     public CommandResult execute(Model model) {
         requireNonNull(model);
-        model.setExpenses(new ArrayList<Expense>());
+        model.setExpenses(new ArrayList<>());
```
Comment (galvinleow) [inline src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java:23]: Although optional to cast ArrayList type, might be good to leave it in?

File: src/main/java/seedu/address/storage/JsonAdaptedTag.java [hunk 3]
```diff
@@ -9,7 +9,7 @@
 /**
  * Jackson-friendly version of {@link Tag}.
  */
-class JsonAdaptedTag {
+public class JsonAdaptedTag {
```
Comment (galvinleow) [inline src/main/java/seedu/address/storage/JsonAdaptedTag.java]: Not sure if protected will be better

File: src/main/java/seedu/address/model/util/attributes/Amount.java [hunk 4]
```diff
@@ -27,7 +27,7 @@
      * The cost of a Service in Singapore Dollars.
      * @param amount double value input representing dollars and cents.
      */
-    public Amount(double amount) {
+    public Amount(Double amount) {
```
Comment (galvinleow) [inline src/main/java/seedu/address/model/util/attributes/Amount.java:30]: I feel that double should remain as a primitive type? If Double means it can accept NULL

File: src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java (hunk 2 above)
Comment (RuiFengg) [reply src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java:23]: Can check out Hans implementation for the clear command that that passes a new service manager (expensetracker for your case)

**Review by RuiFengg — APPROVED** [review]
LGTM, minor changes to be made

**Comment by RuiFengg** [comment]
Consider checking out Galvin's implementation for parse method of find command
